youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Don’t Forget - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=J31Rg_iSNJM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/In ya phone - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=ELqMGdc73QA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Mo money Mo problem - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=xcYTB-lN-xw
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Love Story - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=DXMX44BXJMU
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Oh Momma - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=S8_qN2geP-c
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Crying Out For Me - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=LRNqs1Ch18I
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Last Request - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=eA-VV7TheKc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Free Falling - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=ZD8LMnF-rsk
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Just Dance - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=NikqyfArg3c
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Mad - Jr Aquino - English.%(ext)s" https://www.youtube.com/watch?v=1-SHvwPJIpU
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Perfect - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/NEVER ENOUGH - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/This is me - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/All I ask - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Secret Love Song - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Love me like you do - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/See You Again - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Do You Wanna Build A Snowman  - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Sana maulit muli - Katrina Velarde - Filipino.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Thinking Out Loud - Katrina Velarde - English.%(ext)s" https://www.youtube.com/channel/UCu6hL_eSgFuNAqUZ0D0exNw/videos
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Never be the same - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=KUaCn4MK7yg
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/The Middle  - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=ulzQLOeaez8
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Who’s holding Donna now - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=8YST2SAQWD0
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Gorgeous - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=EgiGENo5HYc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Endless Love - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=wOjiPur8zSU
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Sorry Not Sorry - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=QVazrrhFsAc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Too good at goodbyes - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=FCDNNiDL6zc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/If you're not the one - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=mKabOSlcZY0
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Starlight express - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=0cp8arxonR8
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Wolves - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=NiZPnO5cLKI
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Blue Christmas - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=EOUEZnRxnjo
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Perfect - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=BHBy6wTd224
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/After the love has gone - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=qKCEcSTSW5M
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Hello - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=bc4WM9MsEn4
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/If I believe - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=MRnRD5Bk4nk
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Save the best for last - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=q8L1u1f3teM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/LOVE - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=0ud71w2XX6o
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Best in me - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=E8hd4B0CCeQ
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Swish Swish - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=4WWuPpyRsJE
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Wishing it was you - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=wQWfK17D2f8
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/It's wrong for me to love you - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=SifiVOn7yfI
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Cant you see - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=KG0usb_VaKs
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Numb - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=Ym5IBAaRiLw
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Where are you now - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=UCWCxIV-R4s
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Rockabye - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=OdQU1LMJ9rE
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/My immortal - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=COK1JL0jeac
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/After all - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=pz0LIeGNiNI
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/It takes a man and a woman - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=CZuTSoWmm4U
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Desert moon - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=b2WZCbtfJlE
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Love on the brain  - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=F945gEVW-VM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Mama - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=nCEcpOcmP8c
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Runaway - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=eQr0tep_gxc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Million Reasons - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=gMiD0fsufyo
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/All I wanna do is make love to you - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=kP0ZiblfsAA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/All I ask - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=CckvPbvdz04
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Somewhere down the road - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=B7RCt2_sbng
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Beauty and the beast - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=pqljl8O8aEk
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Versace on the floor - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=VEjDEUaEn9U
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Torn between two lovers - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=QqRD24OpYhA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Victims of love - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=MeAP7WBTAE8
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Careless Whisper - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=fOW-xn15Ytw
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/No More Lonely Nights - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=7-QaMCs2zq8
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Love me tender - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=kJiJR4THeWc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Can't Feel My Face - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=uzqMK_luxPA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/I Love You - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=g2pmwAhEVvs
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/The search is over - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=WhKmPPWfWhM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Be The One - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=6L609TaiPQE
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Send my love - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=nL7Mp-cBCuA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Hero - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=rKtRE_Vm6lM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/The Flame - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=WxYxuxsQLPQ
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Colour of the Night - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=MOv0g7Yacu0
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/One Hello - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=LYKFbRXxtZk
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Honestly - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=cs8BiWU4GgM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Listen To Your Heart - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=5rAuMVUuukc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Aint your mama - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=3yjAaAT80dM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Titanium - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=fbpZzR0BDhQ
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Want to Want Me - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=SPUdTpfN5NU
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/One Call Away - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=TgpeEuV2Sq4
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Lush Life - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=A7rzTT4P8WQ
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/If I Ain't Got You  - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=KftojyvUf-U
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Valentine - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=2hrvMOTOEZw
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Sorry - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=BiNZZpEmyGo
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Valerie - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=_bdoB7BvfZI
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Give Love On Christmas Day - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=WFGNH1-7Icc
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/How deep is your love - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=KCFC8RWQDfM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Like I'm Gonna Lose You - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=1Q6MsQe11wU
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Don't you remember - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=C2KuBL6H9TA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Lay me down - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=zTQacqW0Ocw
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Halo - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=LIivpCaFX4g
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Left Outside Alone - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=yyJAclWBekY
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Love me like you do - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=Ta8rGQKLcy8
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/The closer I get to you - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=UIRn4abh8zs
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Crazy - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=CZZdYlstRwA
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Blank Space - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=XBVLNmE5D54
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Terrified  - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=n37f_cql13E
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Thinking out loud  - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=jIm2Weh-388
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/How long will I love you - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=e7oPAMvDzHQ
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Problem - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=PQvQCrlpaaM
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/I'm yours  - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=YLHPjuahK2M
youtube-dl -f bestaudio --extract-audio --audio-quality 320 --audio-format mp3 -o "wesingBatchDownload/PH Delivery Total_100_Songs_20180511/Tracks/Nothing's gonna stop us now - Mary Ann Van Der Horst - English.%(ext)s" https://www.youtube.com/watch?v=u4sfE9PYq_M
